---
# Test deploy into the server without release the new version
on:
  push:
    # trigger on new tag pushed
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout the development branch
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'development'
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.79.1'
          extended: true

      - name: build with Hugo
        run: |
          git submodule update --init --recursive
          npm install -D --save autoprefixer
          npm install -D --save postcss-cli
          npm install -D postcss
          export HUGO_ENV="production"
          hugo

      - name: copy file into the droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "public/"
          target: "/tmp/golang-aware"


